topicsFilePath: data/topics/topics-task2.xml
qrelsRelevanceFilePath: data/qrels/touche-task2-2022-relevance.qrels
qrelsQualityFilePath: data/qrels/touche-task2-2022-quality.qrels
qrelsStanceFilePath: data/qrels/touche-task2-2022-stance.qrels
runsDirectoryPath: data/runs/
corpusFilePath: data/corpus/touche-task2-passages-version-002.jsonl
cacheDirectoryPath: data/cache/

# Re-ranking with ground-truth stance labels:
#teamRuns:
#- Aldo-Nadi seupd2122-kueri_rrf_reranked
#- Asuna asuna-run-5
#- Captain-Levi levirank_dense_initial_retrieval
#- Captain-Tempesta hextech_run_1
#- Grimjack grimjack-fair-reranking-argumentative-axioms
#- Katana Colbert edinburg
#- Olivier-Armstrong tfid_arg_similarity
#- Puss-in-Boots BM25-Baseline
#runs:
#- {} # original
#- stanceTagger: ground-truth
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#- stanceTagger: ground-truth
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#significanceLevel: 0.05
#effectSize: true
##metricsOutputFilePath: data/metrics-reranking-ground-truth.csv
#metricsOutputFilePath: data/metrics-reranking-ground-truth.tex

# Re-ranking all with ground-truth stance labels:
#runs:
#- {} # original
#- stanceTagger: ground-truth
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#- stanceTagger: ground-truth
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#significanceLevel: 0.05
#effectSize: true
#metricsOutputFilePath: data/metrics-reranking-all-ground-truth.csv

# Re-ranking with team predicted stance labels:
#teamRuns:
#- Aldo-Nadi seupd2122-kueri_rrf_reranked
#- Asuna asuna-run-5
#- Captain-Levi levirank_dense_initial_retrieval
#- Captain-Tempesta hextech_run_1
#- Grimjack grimjack-fair-reranking-argumentative-axioms
#- Katana Colbert edinburg
#- Olivier-Armstrong tfid_arg_similarity
#- Puss-in-Boots BM25-Baseline
#runs:
#- {} # original
#- effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#- effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#significanceLevel: 0.05
#effectSize: true
#metricsOutputFilePath: data/metrics-reranking-original.csv
##metricsOutputFilePath: data/metrics-reranking-original.tex

# Re-ranking all with team predicted stance labels:
#runs:
#- {} # original
#- effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#- effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#significanceLevel: 0.05
#effectSize: true
#metricsOutputFilePath: data/metrics-reranking-all-original.csv

# Stance tagging:
#teamRuns:
#- Aldo-Nadi seupd2122-kueri_rrf_reranked
#- Asuna asuna-run-5
#- Captain-Levi levirank_dense_initial_retrieval
#- Captain-Tempesta hextech_run_1
#- Grimjack grimjack-fair-reranking-argumentative-axioms
#- Katana Colbert edinburg
#- Olivier-Armstrong tfid_arg_similarity
#- Puss-in-Boots BM25-Baseline
#runs:
#- { } # original
#- stanceTagger: ground-truth
#- stanceTagger: google/flan-t5-base
#  stanceTaggerThreshold: 0.5
#  stanceTaggerCutoff: 5
#- stanceTagger: gpt3-tsv
#- stanceTagger: roberta-csv
#measuresStance:
#- F1
#- NumJudged
#- F1@5
#- NumJudged@5
##- FreqFirst
##- FreqSecond
##- FreqNeutral
##- FreqNo
#metricsOutputFilePath: data/metrics-stance-tagging.csv
##metricsOutputFilePath: data/metrics-stance-tagging.tex

# Stance tagging all:
#runs:
#- { } # original
#- stanceTagger: ground-truth
#- stanceTagger: google/flan-t5-base
#  stanceTaggerThreshold: 0.5
#  stanceTaggerCutoff: 5
#- stanceTagger: gpt3-tsv
#- stanceTagger: roberta-csv
#measuresStance:
#- F1
#- NumJudged
#- F1@5
#- NumJudged@5
##- FreqFirst
##- FreqSecond
##- FreqNeutral
##- FreqNo
#metricsOutputFilePath: data/metrics-stance-tagging-all.csv
##metricsOutputFilePath: data/metrics-stance-tagging-all.tex

# Re-ranking with predicted GPT-3 stance labels:
#teamRuns:
#- Aldo-Nadi seupd2122-kueri_rrf_reranked
#- Asuna asuna-run-5
#- Captain-Levi levirank_dense_initial_retrieval
#- Captain-Tempesta hextech_run_1
#- Grimjack grimjack-fair-reranking-argumentative-axioms
#- Katana Colbert edinburg
#- Olivier-Armstrong tfid_arg_similarity
#- Puss-in-Boots BM25-Baseline
#runs:
#- { } # original
#- stanceTagger: gpt3-tsv
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#- stanceTagger: gpt3-tsv
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#significanceLevel: 0.05
#effectSize: true
#metricsOutputFilePath: data/metrics-reranking-gpt3.csv
##metricsOutputFilePath: data/metrics-reranking-gpt3.tex

# Re-ranking all with predicted GPT-3 stance labels:
#runs:
#- { } # original
#- stanceTagger: gpt3-tsv
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#- stanceTagger: gpt3-tsv
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#significanceLevel: 0.05
#effectSize: true
#metricsOutputFilePath: data/metrics-reranking-all-gpt3.csv

# Effect of stance tagger F1 score on improvements:
#runs:
#- {} # original
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 1.00
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.95
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.90
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.85
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.80
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.75
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.70
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.65
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.60
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.55
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.50
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.45
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.40
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.35
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.30
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.25
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.20
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.15
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.10
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.05
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#- stanceTagger: ground-truth
#  stanceRandomizationTargetF1: 0.00
#  stanceRandomizationCutoff: 5
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
#  diversityReranker: alternating-stance
#  diversityRerankerCutoff: 5
#measuresRelevance:
#- nDCG@5
#measuresQuality:
#- nDCG@5
#measuresStance:
#- F1@5
#- rND(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rKL(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#- rRD(group_col='stance_label',tie_breaking='SECOND,FIRST,NEUTRAL,NO',groups='FIRST,SECOND,NEUTRAL')@5
#measuresDiversityRelevance:
#- alpha_nDCG@5
#measuresDiversityQuality:
#- alpha_nDCG@5
#measuresPerQuery: true
metricsOutputFilePath: data/metrics-reranking-all-f1.csv

# Other options:
#maxTeams: 3
#maxRunsPerTeam: 2
#teamRuns:
#- Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_false_porter
#- Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_false_porter_reranked
#- Aldo-Nadi seupd2122-kueri_RF_reranked
#- Aldo-Nadi seupd2122-kueri_rrf
#- Aldo-Nadi seupd2122-kueri_rrf_reranked
#- Asuna asuna-run-5
#- Captain-Levi levirank_voting_retrieval
#- Captain-Levi levirank_psuedo_relevance_feedback
#- Captain-Levi levirank_baseline_large_duo_t5
#- Captain-Levi levirank_dense_initial_retrieval
#- Captain-Levi levirank_psuedo_relevance_feedback+voting
#- Captain-Tempesta hextech_run_1
#- Captain-Tempesta hextech_run_2
#- Captain-Tempesta hextech_run_3
#- Captain-Tempesta hextech_run_4
#- Captain-Tempesta hextech_run_5
#- Grimjack grimjack-baseline
#- Grimjack grimjack-argumentative-axioms
#- Grimjack grimjack-fair-reranking-argumentative-axioms
#- Grimjack grimjack-all-you-need-is-t0
#- Grimjack grimjack-fair-argumentative-reranking-with-t0
#- Katana Colbert fine tune on touche data
#- Katana Colbert trained by me
#- Katana Colbert edinburg
#- Olivier-Armstrong tfid_arg_similarity
#- Puss-in-Boots BM25-Baseline

#significanceLevel: 0.05
#effectSize: true


# Remove documents without judgments before evaluation.
#filterByQrels: true

# Attempt to work offline.
# Won't work unless PyTerrier and NLTK dependencies have previously been downloaded.
#offline: true

openAiApiKey: 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
