topicsFilePath: data/topics/topics-task2.xml
qrelsRelevanceFilePath: data/qrels/touche-task2-2022-relevance.qrels
qrelsQualityFilePath: data/qrels/touche-task2-2022-quality.qrels
qrelsStanceFilePath: data/qrels/touche-task2-2022-stance.qrels
runsDirectoryPath: data/runs/
corpusFilePath: data/corpus/touche-task2-passages-version-002.jsonl
cacheDirectoryPath: data/cache/

runs:
- stanceTagger: original
  stanceReranker: original
  fairnessReranker: original
- stanceTagger: ground-truth
  #stanceTagger: bigscience/T0
  #stanceTagger: bigscience/T0pp
  #stanceTagger: bigscience/T0_3B
  stanceTaggerThreshold: 0.00
  #stanceTaggerThreshold: 0.25
  #stanceTaggerThreshold: 0.50
  stanceTaggerCutoff: 20
  stanceReranker: original
  fairnessReranker: original
- stanceTagger: ground-truth
  stanceTaggerThreshold: 0.00
  stanceTaggerCutoff: 20
  stanceReranker: stance-first # FIRST, SECOND, or NEUTRAL
  #stanceReranker: subjective-stance-first # FIRST or SECOND
  stanceRerankerCutoff: 20
  fairnessReranker: original
- stanceTagger: ground-truth
  stanceTaggerThreshold: 0.00
  stanceTaggerCutoff: 20
  stanceReranker: stance-first
  stanceRerankerCutoff: 20
  fairnessReranker: alternating-stance
  #fairnessReranker: inverse-stance-gain
  #fairnessReranker: boost-minority-stance
  fairnessRerankerCutoff: 20

measuresRelevance:
- nDCG@5
measuresQuality:
- nDCG@5
measuresStance:
#- rND(group_col='stance_label',tie_breaking='group-ascending')@5
#- rKL(group_col='stance_label',tie_breaking='group-ascending')@5
#- rRD(group_col='stance_label',tie_breaking='group-ascending')@5
- rND(group_col='stance_label',tie_breaking='group-ascending',groups='FIRST,SECOND,NEUTRAL')@5
- rKL(group_col='stance_label',tie_breaking='group-ascending',groups='FIRST,SECOND,NEUTRAL')@5
- rRD(group_col='stance_label',tie_breaking='group-ascending',groups='FIRST,SECOND,NEUTRAL')@5
measuresDiversity:
- alpha_nDCG@5
measuresPerQuery: false
#measuresPerQuery: true

significanceLevel: 0.05
significanceAllPairs: false
#significanceAllPairs: true

metricsOutputFilePath: data/metrics.csv
#metricsOutputFilePath: data/metrics.xlsx

# Remove documents without judgments before evaluation.
#filterByQrels: true
filterByQrels: false

# Attempt to work offline.
# Won't work unless PyTerrier and NLTK dependencies have previously been downloaded.
offline: true
