topicsFilePath: data/topics/topics-task2.xml
qrelsRelevanceFilePath: data/qrels/touche-task2-2022-relevance.qrels
qrelsQualityFilePath: data/qrels/touche-task2-2022-quality.qrels
qrelsStanceFilePath: data/qrels/touche-task2-2022-stance.qrels
runsDirectoryPath: data/runs/
corpusFilePath: data/corpus/touche-task2-passages-version-002.jsonl
cacheDirectoryPath: data/cache/

# Re-ranking:
runs:
- {} # original
- stanceTagger: ground-truth
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: original
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: gpt3-tsv
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
#- stanceTagger: google/flan-t5-base
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 1.00
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.95
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.90
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.85
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.80
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.75
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.70
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.65
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.60
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.55
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.50
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.45
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.40
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.35
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.30
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.25
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.20
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
measuresRelevance:
- nDCG@5
measuresQuality:
- nDCG@5
measuresPerQuery: true
metricsOutputFilePath: data/metrics-reranking.csv

## Stance tagging:
#runs:
#- { } # original
#- stanceTagger: ground-truth
#- stanceTagger: google/flan-t5-base
#  stanceTaggerThreshold: 0.5
#  stanceTaggerCutoff: 5
#- stanceTagger: gpt3-tsv
#- stanceTagger: roberta-csv
#measuresStance:
#- F1
#- NumJudged
#- F1@5
#- NumJudged@5
##- FreqFirst
##- FreqSecond
##- FreqNeutral
##- FreqNo
#metricsOutputFilePath: data/metrics-stance-tagging.csv

# Other options:
#maxTeams: 3
#maxRunsPerTeam: 2
#teamRuns:
#- Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_false_porter
#- Aldo-Nadi seupd2122-kueri_kueristopv2_BM2_false_porter_reranked
#- Aldo-Nadi seupd2122-kueri_RF_reranked
#- Aldo-Nadi seupd2122-kueri_rrf
#- Aldo-Nadi seupd2122-kueri_rrf_reranked
#- Asuna asuna-run-5
#- Captain-Levi levirank_voting_retrieval
#- Captain-Levi levirank_psuedo_relevance_feedback
#- Captain-Levi levirank_baseline_large_duo_t5
#- Captain-Levi levirank_dense_initial_retrieval
#- Captain-Levi levirank_psuedo_relevance_feedback+voting
#- Captain-Tempesta hextech_run_1
#- Captain-Tempesta hextech_run_2
#- Captain-Tempesta hextech_run_3
#- Captain-Tempesta hextech_run_4
#- Captain-Tempesta hextech_run_5
#- Grimjack grimjack-baseline
#- Grimjack grimjack-argumentative-axioms
#- Grimjack grimjack-fair-reranking-argumentative-axioms
#- Grimjack grimjack-all-you-need-is-t0
#- Grimjack grimjack-fair-argumentative-reranking-with-t0
#- Katana Colbert fine tune on touche data
#- Katana Colbert trained by me
#- Katana Colbert edinburg
#- Olivier-Armstrong tfid_arg_similarity
#- Puss-in-Boots BM25-Baseline

#significanceLevel: 0.05
#effectSize: true


# Remove documents without judgments before evaluation.
#filterByQrels: true

# Attempt to work offline.
# Won't work unless PyTerrier and NLTK dependencies have previously been downloaded.
#offline: true

openAiApiKey: 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
