topicsFilePath: data/topics/topics-task2.xml
qrelsRelevanceFilePath: data/qrels/touche-task2-2022-relevance.qrels
qrelsQualityFilePath: data/qrels/touche-task2-2022-quality.qrels
qrelsStanceFilePath: data/qrels/touche-task2-2022-stance.qrels
runsDirectoryPath: data/runs/
corpusFilePath: data/corpus/touche-task2-passages-version-002.jsonl
cacheDirectoryPath: data/cache/

#stanceTagger: original
#stanceTagger: ground-truth
#stanceTagger: bigscience/T0
#stanceTagger: bigscience/T0pp
stanceTagger: bigscience/T0_3B
stanceFilterThreshold: 0.5

stanceReranker: original
#stanceReranker: stance-first
#stanceReranker: subjective-stance-first
stanceRerankerCutoff: 10

fairnessReranker: original
#fairnessReranker: alternating-stance # Does not yet work.
fairnessRerankerCutoff: 10

metrics: # Experiment outputs are sorted in by performance in this preference.
  - ndcg_cut_5
  - bpref
  - ndcg_cut_10

# Remove documents without judgments before evaluation.
filterByQrels: true

# Attempt to work offline.
# Won't work unless PyTerrier and NLTK dependencies have previously been downloaded.
# The T0 stance tagger won't work unless all Huggingface API requests were cached previously.
offline: true
