topicsFilePath: data/topics/topics-task2.xml
qrelsRelevanceFilePath: data/qrels/touche-task2-2022-relevance.qrels
qrelsQualityFilePath: data/qrels/touche-task2-2022-quality.qrels
qrelsStanceFilePath: data/qrels/touche-task2-2022-stance.qrels
runsDirectoryPath: data/runs/
corpusFilePath: data/corpus/touche-task2-passages-version-002.jsonl
cacheDirectoryPath: data/cache/

# Re-ranking:
runs:
- { } # original
- stanceTagger: ground-truth
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: original
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: gpt3-tsv
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
#- stanceTagger: google/flan-t5-base
#  effectivenessReranker: stance-first
#  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 1.00
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.95
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.90
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.85
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.80
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.75
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.70
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.65
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.60
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.55
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.50
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.45
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.40
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.35
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.30
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.25
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
- stanceTagger: ground-truth
  stanceRandomizationTargetF1: 0.20
  stanceRandomizationCutoff: 5
  effectivenessReranker: stance-first
  effectivenessRerankerCutoff: 5
measuresRelevance:
- nDCG@5
measuresQuality:
- nDCG@5
metricsOutputFilePath: data/metrics-reranking.csv

## Stance tagging:
#runs:
#- { } # original
#- stanceTagger: ground-truth
#- stanceTagger: google/flan-t5-base
#  stanceTaggerThreshold: 0.5
#  stanceTaggerCutoff: 5
#- stanceTagger: gpt3-tsv
#- stanceTagger: roberta-csv
#measuresStance:
#- F1
#- NumJudged
#- F1@5
#- NumJudged@5
##- FreqFirst
##- FreqSecond
##- FreqNeutral
##- FreqNo
#metricsOutputFilePath: data/metrics-stance-tagging.csv

# Other options:
#maxTeams: 3
#maxRunsPerTeam: 2

# Remove documents without judgments before evaluation.
#filterByQrels: true

openAiApiKey: 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
