topicsFilePath: data/topics/topics-task2.xml
qrelsRelevanceFilePath: data/qrels/touche-task2-2022-relevance.qrels
qrelsQualityFilePath: data/qrels/touche-task2-2022-quality.qrels
qrelsStanceFilePath: data/qrels/touche-task2-2022-stance.qrels
runsDirectoryPath: data/runs/
corpusFilePath: data/corpus/touche-task2-passages-version-002.jsonl
cacheDirectoryPath: data/cache/

#stanceTagger: original
stanceTagger: ground-truth
#stanceTagger: bigscience/T0
#stanceTagger: bigscience/T0pp
#stanceTagger: bigscience/T0_3B
stanceFilterThreshold: 0.00
#stanceFilterThreshold: 0.25
#stanceFilterThreshold: 0.50

stanceReranker: original
#stanceReranker: stance-first # FIRST, SECOND, or NEUTRAL
#stanceReranker: subjective-stance-first # FIRST or SECOND
stanceRerankerCutoff: 20

fairnessReranker: original
#fairnessReranker: alternating-stance
#fairnessReranker: inverse-stance-gain
#fairnessReranker: boost-minority-stance
fairnessRerankerCutoff: 20

#measuresRelevance: [ ]
measuresRelevance:
  - nDCG@5
measuresQuality: [ ]
#measuresQuality:
#  - nDCG@5
#measuresStance: []
measuresStance:
  - rND(groups='FIRST,SECOND,NEUTRAL', group_col='stance_label', tie_breaking='group-ascending')@5
#  - rND(group_col='stance_label', tie_breaking='group-ascending')@5
  - rKL(groups='FIRST,SECOND,NEUTRAL', group_col='stance_label', tie_breaking='group-ascending')@5
#  - rKL(group_col='stance_label', tie_breaking='group-ascending')@5
  - rRD(groups='FIRST,SECOND,NEUTRAL', group_col='stance_label', tie_breaking='group-ascending')@5
#  - rRD(group_col='stance_label', tie_breaking='group-ascending')@5
measuresPerQuery: false

# Remove documents without judgments before evaluation.
filterByQrels: true

# Attempt to work offline.
# Won't work unless PyTerrier and NLTK dependencies have previously been downloaded.
offline: true
